// Non-invasive links: preserves existing modules, permissions and login flow.
(()=>{'use strict';const root=new URL('.',document.currentScript.src);const url=p=>new URL(p,root).href;
function link(parent,id,label,target,css=''){if(!parent||document.getElementById(id))return;const a=document.createElement('a');a.id=id;a.href=url(target);a.textContent=label;a.className=css;parent.appendChild(a);return a;}
function attach(){if(document.body.dataset.beneficiosPage)return;
 const isAdmin=location.pathname.includes('/gestion/');
 if(isAdmin){const more=document.querySelector('.more-panel');link(more,'beneficios-tools','🎁 Beneficios y convenios','gestion/beneficios.html');const aside=document.querySelector('aside');const a=link(aside,'beneficios-side','🎁 Beneficios y convenios','gestion/beneficios.html');if(a)a.style.cssText='display:block;padding:12px 10px;color:#ffb889;text-decoration:none;font-size:12px;font-weight:800;border-top:1px solid #fff2;margin-top:10px';
 if(!aside){const host=document.querySelector('.top .in,.top .topin,header .wrap');link(host,'beneficios-admin-link',' · Beneficios y convenios','gestion/beneficios.html');}return;}
 link(document.getElementById('gb-drawer'),'beneficios-menu','🎁 Beneficios Gigantes','beneficios.html');
 const bottom=document.getElementById('gb-bottomnav');if(bottom&&!document.getElementById('beneficios-bottom')){const a=document.createElement('a');a.id='beneficios-bottom';a.href=url('beneficios.html');a.innerHTML='<span>🎁</span><small>Beneficios</small>';bottom.insertBefore(a,bottom.lastElementChild);bottom.style.gridTemplateColumns='repeat(5,1fr)';}
 const home=document.querySelector('.grid4');if(home&&!document.getElementById('beneficios-home')){const c=document.createElement('div');c.id='beneficios-home';c.className='card';c.innerHTML='<div class="icon">🎁</div><h3>Beneficios Gigantes</h3><p>Convenios, Hincha Gigante y empresas que apoyan al club.</p>';link(c,'beneficios-home-link','Conocer beneficios →','beneficios.html');home.appendChild(c);}
 const portal=document.getElementById('portal');if(portal&&!document.getElementById('beneficios-portal')){const c=document.createElement('div');c.id='beneficios-portal';c.className='card';c.style.marginTop='14px';c.innerHTML='<h2>🎁 Beneficios Gigantes</h2><p>Conoce los convenios y la membresía Hincha Gigante. Credenciales digitales pendientes de habilitación.</p>';link(c,'beneficios-portal-link','VER BENEFICIOS','beneficios.html','btn');portal.appendChild(c);}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',attach,{once:true});else attach();window.addEventListener('load',attach,{once:true});})();
