// Gigantes de Azapa · shell global de producción
const GIGANTES={LOGO:"https://raw.githubusercontent.com/gigantesazapasalta2026-sudo/gigantes-media-archive/main/LOGO%20GIGANTES.jpeg",BASE:new URL("./",window.location.href).href,FOTOS:{video:"https://raw.githubusercontent.com/gigantesazapasalta2026-sudo/gigantes-media-archive/main/medios/club/ni%C3%B1os%20llegando%20a%20jugar.mov",m10m12:"https://raw.githubusercontent.com/gigantesazapasalta2026-sudo/gigantes-media-archive/main/m10m12.jpg",entrenadores:"https://raw.githubusercontent.com/gigantesazapasalta2026-sudo/gigantes-media-archive/main/Entrenadores.jpg",ninos2:"https://raw.githubusercontent.com/gigantesazapasalta2026-sudo/gigantes-media-archive/main/Ni%C3%B1os%20reunidos%202.jpg",tercer:"https://raw.githubusercontent.com/gigantesazapasalta2026-sudo/gigantes-media-archive/main/3er%20tiempo.jpg",fogata:"https://raw.githubusercontent.com/gigantesazapasalta2026-sudo/gigantes-media-archive/main/fogata%20formando%20club.jpg",estadio:"Rugby estadio.jpg",playa:"https://raw.githubusercontent.com/gigantesazapasalta2026-sudo/gigantes-media-archive/main/rugby%20playa.jpg"},PAGINA_FOTO:{inscripcion:"ninos2",documentos_carga:"entrenadores",actividades:"tercer",bingos:"fogata",aportes:"estadio",sponsors:"playa",avance:"estadio",galeria_club:"entrenadores",itinerario:"ninos2",merchandising:"m10m12",album_equipo:"m10m12",index:"ninos2",vision:"fogata",recaudacion:"tercer",default:"ninos2"}};
function injectTopbar(){
 if(document.getElementById("gb-topbar"))return;
 const css=document.createElement("style");
 css.textContent=`#gb-topbar{position:fixed;top:0;left:0;right:0;z-index:9000;display:flex;align-items:center;justify-content:space-between;padding:9px 14px;background:rgba(11,15,20,.96);backdrop-filter:blur(14px);border-bottom:1px solid rgba(255,255,255,.12);font-family:Arial,sans-serif}#gb-topbar .gb-brand{display:flex;align-items:center;gap:9px;color:#fff;text-decoration:none;font-weight:900}#gb-topbar .gb-brand img{width:40px;height:40px;border-radius:50%;object-fit:cover;background:#fff;padding:2px}#gb-topbar small{display:block;color:#f36b21;font-size:.6rem;text-transform:uppercase;letter-spacing:.5px}#gb-topbar span{font-size:.86rem}#gb-topbar .gb-btn{width:40px;height:40px;border:1px solid rgba(255,255,255,.18);border-radius:9px;background:#ffffff10;color:#fff;font-size:1.3rem}#gb-drawer{display:none;position:fixed;top:0;right:0;z-index:9999;width:min(330px,92vw);height:100vh;background:#fff;padding:18px;box-shadow:-20px 0 60px rgba(0,0,0,.45);overflow:auto;font-family:Arial,sans-serif}#gb-drawer.open{display:block}#gb-drawer .gb-dh{display:flex;align-items:center;justify-content:space-between;margin-bottom:14px}#gb-drawer .gb-x{width:38px;height:38px;border:0;border-radius:8px;background:#111;color:#fff}#gb-drawer a{display:flex;align-items:center;gap:9px;color:#111;text-decoration:none;border-left:4px solid #f36b21;background:#fff7ed;border-radius:0 8px 8px 0;padding:10px 13px;margin:5px 0;font-weight:800;font-size:.86rem}#gb-bottomnav{display:none}body{padding-top:58px!important}@media(max-width:760px){body{padding-bottom:72px!important}#gb-bottomnav{display:grid;grid-template-columns:repeat(4,1fr);position:fixed;left:0;right:0;bottom:0;z-index:8999;background:rgba(11,15,20,.97);backdrop-filter:blur(14px);border-top:1px solid rgba(255,255,255,.12);padding:6px 6px calc(6px + env(safe-area-inset-bottom));font-family:Arial,sans-serif}#gb-bottomnav a{display:flex;flex-direction:column;align-items:center;gap:2px;color:#fff;text-decoration:none;padding:5px 2px}#gb-bottomnav span{font-size:1.2rem}#gb-bottomnav small{font-size:.6rem;color:#d1d5db;font-weight:700}}`;
 document.head.appendChild(css);
 const B=GIGANTES.BASE;
 const bar=document.createElement("header");bar.id="gb-topbar";
 bar.innerHTML=`<a class="gb-brand" href="${B}index.html"><img src="https://raw.githubusercontent.com/gigantesazapasalta2026-sudo/gigantes-media-archive/main/LOGO%20GIGANTES.jpeg" alt="Gigantes de Azapa"><div><small>Gigantes de Azapa</small><span>Club Deportivo · Arica</span></div></a><button class="gb-btn" aria-label="Abrir menú" onclick="document.getElementById('gb-drawer').classList.toggle('open')">☰</button>`;
 document.body.insertBefore(bar,document.body.firstChild);
 const nav=document.createElement("nav");nav.id="gb-drawer";
 nav.innerHTML=`<div class="gb-dh"><strong>Menú</strong><button class="gb-x" aria-label="Cerrar" onclick="document.getElementById('gb-drawer').classList.remove('open')">✕</button></div>
 <a href="${B}index.html">🏠 Portada</a><a href="${B}novedades.html">📣 Novedades</a><a href="${B}eventos.html">📅 Eventos y actividades</a><a href="${B}mi_jugador.html">👤 Mi Gigantes</a><a href="${B}lesionado.html">🚑 Jugador lesionado</a><a href="${B}proyectos.html">🗂️ Proyectos y giras</a><a href="${B}vision.html">🎯 Visión 2026–2030</a><a href="${B}recaudacion.html">💰 Recaudación y comunidad</a><a href="${B}inscripcion.html">🏉 Unirse al club</a><a href="${B}album_equipo.html">⭐ Equipos</a><a href="${B}galeria_club.html">📸 Galería</a><a href="${B}merchandising.html">👕 Merchandising</a><a href="${B}sponsors.html">🤝 Sponsors</a><a href="${B}aportes.html">💛 Aportes</a><a href="${B}gestion/login.html">🔐 Acceso privado</a>`;
 document.body.appendChild(nav);
 const bottom=document.createElement("nav");bottom.id="gb-bottomnav";
 bottom.innerHTML=`<a href="${B}index.html"><span>🏠</span><small>Inicio</small></a><a href="${B}novedades.html"><span>📣</span><small>Novedades</small></a><a href="${B}eventos.html"><span>📅</span><small>Eventos</small></a><a href="${B}mi_jugador.html"><span>👤</span><small>Mi Gigantes</small></a>`;
 document.body.appendChild(bottom);
 document.addEventListener("click",e=>{const d=document.getElementById("gb-drawer");if(d&&!d.contains(e.target)&&!e.target.classList.contains("gb-btn"))d.classList.remove("open")});
}
function injectHeroBg(){const hero=document.querySelector(".hero,header.hero,.hero-header");if(!hero||hero.querySelector(".gb-bg"))return;const page=location.pathname.split("/").pop().replace(/\.html?$/,"")||"index",key=GIGANTES.PAGINA_FOTO[page]||"default",file=GIGANTES.FOTOS[key]||GIGANTES.FOTOS.ninos2;hero.style.position="relative";hero.style.overflow="hidden";const bg=document.createElement("div");bg.className="gb-bg";bg.style.cssText=`position:absolute;inset:0;z-index:0;background:url("${encodeURI(file)}") center/cover`;const ov=document.createElement("div");ov.style.cssText="position:absolute;inset:0;z-index:1;background:linear-gradient(180deg,rgba(11,15,20,.38),rgba(11,15,20,.9))";hero.prepend(ov);hero.prepend(bg);Array.from(hero.children).forEach(x=>{if(x!==bg&&x!==ov){x.style.position="relative";x.style.zIndex="2"}})}
function fixLogos(){document.querySelectorAll("img").forEach(img=>{const s=img.getAttribute("src")||"";if(s.includes("01_APP_SITIO_WEB")||s.includes("logo-gigantes")||s.includes("LOGO GIGANTES.jpeg")||s.includes("lh3.google"))img.src="https://raw.githubusercontent.com/gigantesazapasalta2026-sudo/gigantes-media-archive/main/LOGO%20GIGANTES.jpeg"})}
function init(){injectTopbar();injectHeroBg();fixLogos()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();window.addEventListener("load",fixLogos);
