import {esc,safeUrl,today,dateLabel,money,client,result} from '../beneficios-core.js';
const $=id=>document.getElementById(id);const root=new URL('../',document.baseURI);let sb,partners=[],promos=[],agreements=[],requests=[],units=[],supporters=[],supporterPayments=[],people=[],profiles=[],companyAccess=[],editing=null;
const typeLabels={pending:'Por acordar',monthly:'Mensual',annual:'Anual',in_kind:'En productos o servicios',campaign:'Campaña'};
const stateLabels={draft:'Borrador',approved:'Acuerdo aprobado',closed:'Cerrado'};
async function refresh(){
 const responses=await Promise.all([sb.from('benefit_partners').select('*').order('name'),sb.from('benefit_promotions').select('*').order('ends_on',{ascending:false}),sb.from('benefit_agreements').select('*'),sb.from('sponsor_inquiries').select('id,organization,contact_name,email,phone,interest,message,status,created_at').eq('project_code','BENEFICIOS').order('created_at',{ascending:false}).limit(500),sb.from('treasury_units').select('id,name,code').eq('active',true).order('name'),sb.from('benefit_supporters').select('*').order('created_at',{ascending:false}),sb.from('benefit_supporter_payments').select('*').order('created_at',{ascending:false}).limit(1000),sb.from('people').select('id,full_name,email,phone').order('full_name'),sb.from('profiles').select('user_id,display_name,role,active').eq('active',true).order('display_name'),sb.from('benefit_company_access').select('*')]);
 const bad=responses.find(x=>x.error);if(bad)throw bad.error;
 [partners,promos,agreements,requests,units,supporters,supporterPayments,people,profiles,companyAccess]=responses.map(x=>x.data||[]);render();
}
function render(){
 const hinchas=requests.filter(r=>r.interest==='hincha_gigante'),companies=requests.filter(r=>r.interest!=='hincha_gigante');
 $('count-partners').textContent=partners.length;$('count-hinchas').textContent=supporters.filter(x=>x.status==='active').length;$('count-companies').textContent=companies.length;
 $('partner-list').innerHTML=partners.length?partners.map(p=>{const a=agreements.find(x=>x.partner_id===p.id),va=companyAccess.filter(x=>x.partner_id===p.id&&x.active),validatorNames=va.map(x=>profiles.find(y=>y.user_id===x.user_id)?.display_name||x.user_id);return `<article class="list-row"><div><span class="tag ${p.active?'':'gray'}">${p.active?'Publicación activa':'Sin publicar'}</span><h3>${esc(p.name)}</h3><p>${esc(p.benefit_title)}</p><p class="small muted">${esc(dateLabel(p.starts_on))} · ${esc(dateLabel(p.ends_on))}</p><p class="small"><strong>Aporte privado:</strong> ${esc(typeLabels[a?.contribution_type]||'Por acordar')} ${a?.amount!=null?'· '+esc(money(a.amount)):''} · ${esc(stateLabels[a?.status]||'Borrador')}</p><p class="small muted">${esc(a?.terms||'Sin compromiso registrado. No acredita un aporte recibido.')}</p><p class="small"><strong>Validadores:</strong> ${validatorNames.length?validatorNames.map(esc).join(' · '):'Sin cuentas autorizadas'}</p><div class="actions"><select id="validator-${p.id}" aria-label="Cuenta para validar"><option value="">Elegir cuenta…</option>${profiles.map(x=>`<option value="${x.user_id}">${esc(x.display_name||x.user_id)} · ${esc(x.role)}</option>`).join('')}</select><button class="btn small" data-grant-validator="${p.id}">Dar acceso</button>${va.map(x=>`<button class="btn small" data-revoke-validator="${p.id}" data-validator-user="${x.user_id}">Quitar ${esc(profiles.find(y=>y.user_id===x.user_id)?.display_name||'acceso')}</button>`).join('')}</div></div><div class="actions"><button class="btn small" data-edit-partner="${p.id}">Editar ficha</button><button class="btn small" data-agreement="${p.id}">Acuerdo de aporte</button></div></article>`;}).join(''):'<p class="muted">No hay empresas registradas.</p>';
 $('promotion-list').innerHTML=promos.length?promos.map(p=>`<article class="list-row"><div><span class="tag">${p.active?'Publicación activa':'Borrador'}</span><h3>${esc(p.title)}</h3><p>${esc(partners.find(x=>x.id===p.partner_id)?.name||'Empresa')}</p><p class="small muted">${p.audience==='public'?'Público general':'Miembros'} · ${esc(dateLabel(p.starts_on))} — ${esc(dateLabel(p.ends_on))}</p><p>${esc(p.description)}</p></div><button class="btn small" data-edit-promo="${p.id}">Editar</button></article>`).join(''):'<p class="muted">Todavía no hay promociones. El descuento de Astor está en su ficha de convenio.</p>';
 $('hincha-list').innerHTML=hinchaRequestList(hinchas);$('supporter-list').innerHTML=supporterList();$('company-list').innerHTML=requestList(companies);
}
function currentMonth(){const d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0');return y+'-'+m+'-01'}
function personName(id){return people.find(p=>p.id===id)?.full_name||'Hincha'}
function supporterList(){
 const month=currentMonth(),active=supporters.filter(s=>s.status==='active');
 return active.length?active.map(s=>{const pay=supporterPayments.find(p=>p.supporter_id===s.id&&p.period===month&&p.status==='verified'),unit=units.find(u=>u.id===s.treasury_unit_id);return `<article class="list-row"><div><span class="tag ${pay?'':'gray'}">${pay?'Al día':'Pendiente'}</span><h3>${esc(personName(s.person_id))}</h3><p class="small muted">${esc(unit?.name||'Tesorería no asignada')} · ${esc(dateLabel(s.joined_at))}</p>${pay?`<p class="small">Pago ${esc(money(pay.amount))} · ${esc(pay.payment_date)} · ref. ${esc(pay.reference)}</p>`:''}</div><div class="actions">${pay?`<button class="btn small" data-cancel-supporter-payment="${pay.id}">Anular pago</button>`:`<button class="btn small primary" data-supporter-pay="${s.id}">Registrar $2.000</button>`}</div></article>`;}).join(''):'<p class="muted">Todavía no hay Hinchas Gigantes activos.</p>';
}
function hinchaRequestList(list){
 const pending=list.filter(r=>r.status!=='closed');
 return pending.length?pending.map(r=>`<article class="list-row"><div><span class="tag gray">${esc(({new:'Nueva',contacted:'Contactada'})[r.status]||r.status)}</span><h3>${esc(r.contact_name)}</h3><p class="small">${esc(r.email)} · ${esc(r.phone)}</p><p class="small muted">${esc(dateLabel(r.created_at))}</p><p class="small">${esc(r.message)}</p></div><div class="actions"><button class="btn small primary" data-activate-supporter="${r.id}">Activar Hincha</button><button class="btn small" data-request="${r.id}" data-status="contacted">Marcar contactada</button><button class="btn small" data-request="${r.id}" data-status="closed">Cerrar solicitud</button></div></article>`).join(''):'<p class="muted">No hay solicitudes pendientes de Hincha Gigante.</p>';
}
function requestList(list){return list.length?list.map(r=>`<article class="list-row"><div><span class="tag gray">${esc(({new:'Nueva',contacted:'Contactada',closed:'Cerrada'})[r.status]||r.status)}</span><h3>${esc(r.interest==='hincha_gigante'?r.contact_name:r.organization)}</h3><p class="small">${esc(r.contact_name)} · ${esc(r.email)} · ${esc(r.phone)}</p><p class="small muted">${esc(dateLabel(r.created_at))}</p><p class="small">${esc(r.message)}</p></div><div class="actions"><button class="btn small" data-request="${r.id}" data-status="contacted">Marcar contactada</button><button class="btn small" data-request="${r.id}" data-status="closed">Cerrar solicitud</button></div></article>`).join(''):'<p class="muted">No hay solicitudes registradas en esta bandeja.</p>';}
function field(name,label,value='',type='text',extra=''){return `<div class="field"><label for="f-${name}">${esc(label)}</label><input id="f-${name}" name="${name}" type="${type}" value="${esc(value??'')}" ${extra}></div>`;}
function area(name,label,value='',required=false){return `<div class="field span2"><label for="f-${name}">${esc(label)}</label><textarea id="f-${name}" name="${name}" maxlength="2000" ${required?'required':''}>${esc(value||'')}</textarea></div>`;}
function checkbox(name,label,checked=false){return `<label class="check"><input name="${name}" type="checkbox" ${checked?'checked':''}>${esc(label)}</label>`;}
function select(name,label,options,value=''){return `<div class="field"><label for="f-${name}">${esc(label)}</label><select id="f-${name}" name="${name}">${options.map(([v,l])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(l)}</option>`).join('')}</select></div>`;}
function showEditor(type,id,title,html){editing={type,id};$('editor-title').textContent=title;$('editor-fields').innerHTML=html;$('editor-result').textContent='';$('editor').showModal();}
function editPartner(id){const p=partners.find(x=>x.id===id)||{};showEditor('partner',id,id?'Editar empresa':'Agregar empresa',field('name','Nombre de empresa',p.name,'text','required minlength="2" maxlength="180"')+field('slug','Identificador (minúsculas y guiones)',p.slug,'text','required pattern="[a-z0-9-]{2,80}"')+field('category','Categoría',p.category||'Comercio','text','required maxlength="80"')+field('discount_percent','Descuento (%) — dejar vacío si no aplica',p.discount_percent,'number','min="0" max="100" step="0.01"')+field('benefit_title','Título del beneficio',p.benefit_title,'text','required maxlength="200"')+field('website','Sitio web HTTPS',p.website,'url')+field('whatsapp','WhatsApp (código país + número)',p.whatsapp,'text','maxlength="20"')+field('address','Dirección o sedes',p.address,'text','maxlength="400"')+field('logo_url','URL del logo o ruta dentro de la app',p.logo_url)+field('secondary_logo_url','Segundo logo (opcional)',p.secondary_logo_url)+field('starts_on','Inicio del convenio',p.starts_on||today(),'date','required')+field('ends_on','Término (opcional)',p.ends_on,'date')+area('description','Descripción de la empresa',p.description)+area('conditions','Condiciones del beneficio',p.conditions,true)+checkbox('active','Publicar ficha del convenio',p.active)+checkbox('featured','Destacar empresa',p.featured));}
function editAgreement(id){const a=agreements.find(x=>x.partner_id===id)||{};showEditor('agreement',id,'Acuerdo privado de aporte',select('contribution_type','Modalidad',Object.entries(typeLabels),a.contribution_type||'pending')+field('amount','Monto CLP (vacío cuando no está acordado)',a.amount,'number','min="0" step="1"')+select('status','Estado',Object.entries(stateLabels),a.status||'draft')+select('treasury_unit_id','Tesorería responsable',[['','Pendiente de asignar'],...units.map(u=>[u.id,u.name])],a.treasury_unit_id||'')+area('terms','Acuerdo, periodicidad y alcance',a.terms,true)+'<p class="small muted span2">No genera cargos ni movimientos de Tesorería. Registrar un acuerdo no acredita que el club haya recibido dinero.</p>');}
function editPromo(id){if(!partners.length){result($('admin-result'),'Primero agrega la empresa.',true);return;}const p=promos.find(x=>x.id===id)||{};showEditor('promo',id,id?'Editar promoción':'Nueva promoción',select('partner_id','Empresa',partners.map(x=>[x.id,x.name]),p.partner_id||partners[0].id)+field('title','Título',p.title,'text','required minlength="2" maxlength="180"')+select('audience','Público',[['members','Miembros vigentes'],['public','Público general']],p.audience||'members')+field('starts_on','Inicio',p.starts_on||today(),'date','required')+field('ends_on','Fin',p.ends_on,'date','required')+area('description','Contenido y condiciones',p.description,true)+checkbox('active','Publicar durante las fechas indicadas',p.active));}
$('editor-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;if(!form.reportValidity()||!editing)return;const f=new FormData(form),get=k=>String(f.get(k)||'').trim(),button=form.querySelector('button[type=submit]');if(button.disabled)return;button.disabled=true;const {type,id}=editing;try{
 let q;
 if(type==='partner'){
  for(const key of ['website','logo_url','secondary_logo_url'])if(get(key)&&!safeUrl(get(key),root))throw new Error('Los enlaces deben usar HTTPS o una ruta de la aplicación.');
  if(get('ends_on')&&get('ends_on')<get('starts_on'))throw new Error('La fecha de término no puede ser anterior al inicio.');
  const p=Object.fromEntries(['name','slug','category','benefit_title','website','whatsapp','address','logo_url','secondary_logo_url','starts_on','description','conditions'].map(k=>[k,get(k)]));p.ends_on=get('ends_on')||null;p.discount_percent=get('discount_percent')===''?null:Number(get('discount_percent'));p.active=f.has('active');p.featured=f.has('featured');p.updated_at=new Date().toISOString();
  q=id?sb.from('benefit_partners').update(p).eq('id',id).select('id').single():sb.from('benefit_partners').insert(p).select('id').single();
 }else if(type==='agreement'){
  const a={partner_id:id,contribution_type:get('contribution_type'),amount:get('amount')===''?null:Number(get('amount')),status:get('status'),treasury_unit_id:get('treasury_unit_id')||null,terms:get('terms'),updated_at:new Date().toISOString()};
  if(a.status==='approved'&&(!a.treasury_unit_id||a.contribution_type==='pending'||(['monthly','annual'].includes(a.contribution_type)&&!(a.amount>0))))throw new Error('Para aprobar, define modalidad, tesorería y monto cuando corresponda.');
  q=sb.from('benefit_agreements').upsert(a,{onConflict:'partner_id'}).select('partner_id').single();
 }else{
  if(get('ends_on')<get('starts_on'))throw new Error('Revisa las fechas de la promoción.');const p={partner_id:get('partner_id'),title:get('title'),description:get('description'),audience:get('audience'),starts_on:get('starts_on'),ends_on:get('ends_on'),active:f.has('active')};
  q=id?sb.from('benefit_promotions').update(p).eq('id',id).select('id').single():sb.from('benefit_promotions').insert(p).select('id').single();
 }
 const r=await q;if(r.error)throw r.error;$('editor').close();result($('admin-result'),'Cambios guardados en la base de datos.');try{await refresh();}catch{result($('admin-result'),'Guardado confirmado. Recarga la página para actualizar la vista.',true);}
 }catch(e){result($('editor-result'),e.message||'No fue posible guardar los cambios.',true);}finally{button.disabled=false;}});
$('close-editor').onclick=$('cancel-editor').onclick=()=>$('editor').close();
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.tab){document.querySelectorAll('[data-tab]').forEach(x=>x.setAttribute('aria-selected',String(x===b)));['partners','promos','hinchas','companies'].forEach(t=>$('panel-'+t).hidden=t!==b.dataset.tab);}
 if(b.dataset.editPartner)editPartner(b.dataset.editPartner);if(b.dataset.agreement)editAgreement(b.dataset.agreement);if(b.dataset.editPromo)editPromo(b.dataset.editPromo);
 if(b.dataset.grantValidator){const uid=document.getElementById('validator-'+b.dataset.grantValidator)?.value;if(!uid)return result($('admin-result'),'Selecciona una cuenta activa.',true);b.disabled=true;try{const r=await sb.from('benefit_company_access').upsert({partner_id:b.dataset.grantValidator,user_id:uid,active:true},{onConflict:'partner_id,user_id'});if(r.error)throw r.error;await refresh();result($('admin-result'),'Cuenta autorizada para validar este convenio.');}catch(err){result($('admin-result'),err.message||'No fue posible autorizar la cuenta.',true);}finally{b.disabled=false;}}
 if(b.dataset.revokeValidator){if(!confirm('¿Quitar acceso de validación a esta cuenta?'))return;b.disabled=true;try{const r=await sb.from('benefit_company_access').update({active:false}).eq('partner_id',b.dataset.revokeValidator).eq('user_id',b.dataset.validatorUser);if(r.error)throw r.error;await refresh();result($('admin-result'),'Acceso de validación retirado.');}catch(err){result($('admin-result'),err.message||'No fue posible retirar el acceso.',true);}finally{b.disabled=false;}}
 if(b.dataset.activateSupporter){if(b.disabled)return;const defaultUnit=units.find(u=>u.code==='GIGANTES')||units[0];const unitId=prompt('ID de Tesorería para este Hincha:',defaultUnit?.id||'');if(!unitId)return;b.disabled=true;try{const r=await sb.rpc('activate_benefit_supporter_from_request',{p_request_id:b.dataset.activateSupporter,p_treasury_unit_id:unitId});if(r.error)throw r.error;await refresh();result($('admin-result'),'Hincha activado correctamente. Aún no está al día hasta registrar su mensualidad de $2.000.');}catch(err){result($('admin-result'),err.message||'No fue posible activar al Hincha.',true);}finally{b.disabled=false;}}
 if(b.dataset.supporterPay){if(b.disabled)return;const ref=prompt('Referencia del pago (transferencia/efectivo):');if(!ref?.trim())return;const method=prompt('Medio: transfer / cash / card / other','transfer')||'transfer';if(!['transfer','cash','card','other'].includes(method))return result($('admin-result'),'Medio de pago no válido.',true);b.disabled=true;try{const r=await sb.rpc('record_benefit_supporter_payment',{p_supporter_id:b.dataset.supporterPay,p_period:currentMonth(),p_payment_date:new Date().toISOString().slice(0,10),p_payment_method:method,p_reference:ref.trim()});if(r.error)throw r.error;await refresh();result($('admin-result'),'Pago de Hincha registrado en Tesorería y membresía al día.');}catch(err){result($('admin-result'),err.message||'No fue posible registrar el pago.',true);}finally{b.disabled=false;}}
 if(b.dataset.cancelSupporterPayment){if(b.disabled)return;const reason=prompt('Motivo de anulación del pago:');if(!reason?.trim())return;if(!confirm('¿Anular este pago de Hincha? Se generará una reversa en Tesorería.'))return;b.disabled=true;try{const r=await sb.rpc('cancel_benefit_supporter_payment',{p_payment_id:b.dataset.cancelSupporterPayment,p_reason:reason.trim()});if(r.error)throw r.error;await refresh();result($('admin-result'),'Pago anulado y reversa contable registrada.');}catch(err){result($('admin-result'),err.message||'No fue posible anular el pago.',true);}finally{b.disabled=false;}}
 if(b.dataset.request){if(b.disabled)return;b.disabled=true;try{const r=await sb.from('sponsor_inquiries').update({status:b.dataset.status,updated_at:new Date().toISOString()}).eq('id',b.dataset.request).eq('project_code','BENEFICIOS').select('id').single();if(r.error)throw r.error;await refresh();result($('admin-result'),'Estado de seguimiento actualizado.');}catch(err){result($('admin-result'),'No se pudo actualizar el estado. Recarga y vuelve a intentarlo.',true);}finally{b.disabled=false;}}
});
$('new-partner').onclick=()=>editPartner(null);$('new-promotion').onclick=()=>editPromo(null);
(async()=>{try{sb=client();const {data,error}=await sb.auth.getSession();if(error)throw error;if(!data.session){location.replace('login.html?next=beneficios.html');return;}const r=await sb.from('profiles').select('role,active').eq('user_id',data.session.user.id).maybeSingle();if(r.error)throw r.error;if(!r.data?.active||!['superadmin','board'].includes(r.data.role)){$('access-state').textContent='Este módulo está reservado a la directiva autorizada. La gestión no está disponible para esta cuenta.';return;}await refresh();$('access-state').hidden=true;$('admin-app').hidden=false;}catch(e){$('access-state').textContent='No pudimos verificar o cargar el módulo. Recarga la página; no se han cambiado datos.';}})();
