import {esc,safeUrl,today,dateLabel,money,client,result} from '../beneficios-core.js';
const $=id=>document.getElementById(id);const root=new URL('../',document.baseURI);let sb,partners=[],promos=[],agreements=[],requests=[],units=[],editing=null;
const typeLabels={pending:'Por acordar',monthly:'Mensual',annual:'Anual',in_kind:'En productos o servicios',campaign:'Campaña'};
const stateLabels={draft:'Borrador',approved:'Acuerdo aprobado',closed:'Cerrado'};
async function refresh(){
 const responses=await Promise.all([sb.from('benefit_partners').select('*').order('name'),sb.from('benefit_promotions').select('*').order('ends_on',{ascending:false}),sb.from('benefit_agreements').select('*'),sb.from('sponsor_inquiries').select('id,organization,contact_name,email,phone,interest,message,status,created_at').eq('project_code','BENEFICIOS').order('created_at',{ascending:false}).limit(500),sb.from('treasury_units').select('id,name').eq('active',true).order('name')]);
 const bad=responses.find(x=>x.error);if(bad)throw bad.error;
 [partners,promos,agreements,requests,units]=responses.map(x=>x.data||[]);render();
}
function render(){
 const hinchas=requests.filter(r=>r.interest==='hincha_gigante'),companies=requests.filter(r=>r.interest!=='hincha_gigante');
 $('count-partners').textContent=partners.length;$('count-hinchas').textContent=hinchas.length;$('count-companies').textContent=companies.length;
 $('partner-list').innerHTML=partners.length?partners.map(p=>{const a=agreements.find(x=>x.partner_id===p.id);return `<article class="list-row"><div><span class="tag ${p.active?'':'gray'}">${p.active?'Publicación activa':'Sin publicar'}</span><h3>${esc(p.name)}</h3><p>${esc(p.benefit_title)}</p><p class="small muted">${esc(dateLabel(p.starts_on))} · ${esc(dateLabel(p.ends_on))}</p><p class="small"><strong>Aporte privado:</strong> ${esc(typeLabels[a?.contribution_type]||'Por acordar')} ${a?.amount!=null?'· '+esc(money(a.amount)):''} · ${esc(stateLabels[a?.status]||'Borrador')}</p><p class="small muted">${esc(a?.terms||'Sin compromiso registrado. No acredita un aporte recibido.')}</p></div><div class="actions"><button class="btn small" data-edit-partner="${p.id}">Editar ficha</button><button class="btn small" data-agreement="${p.id}">Acuerdo de aporte</button></div></article>`;}).join(''):'<p class="muted">No hay empresas registradas.</p>';
 $('promotion-list').innerHTML=promos.length?promos.map(p=>`<article class="list-row"><div><span class="tag">${p.active?'Publicación activa':'Borrador'}</span><h3>${esc(p.title)}</h3><p>${esc(partners.find(x=>x.id===p.partner_id)?.name||'Empresa')}</p><p class="small muted">${p.audience==='public'?'Público general':'Miembros'} · ${esc(dateLabel(p.starts_on))} — ${esc(dateLabel(p.ends_on))}</p><p>${esc(p.description)}</p></div><button class="btn small" data-edit-promo="${p.id}">Editar</button></article>`).join(''):'<p class="muted">Todavía no hay promociones. El descuento de Astor está en su ficha de convenio.</p>';
 $('hincha-list').innerHTML=requestList(hinchas);$('company-list').innerHTML=requestList(companies);
}
function requestList(list){return list.length?list.map(r=>`<article class="list-row"><div><span class="tag gray">${esc(({new:'Nueva',contacted:'Contactada',closed:'Cerrada'})[r.status]||r.status)}</span><h3>${esc(r.interest==='hincha_gigante'?r.contact_name:r.organization)}</h3><p class="small">${esc(r.contact_name)} · ${esc(r.email)} · ${esc(r.phone)}</p><p class="small muted">${esc(dateLabel(r.created_at))}</p><p class="small">${esc(r.message)}</p></div><div class="actions"><button class="btn small" data-request="${r.id}" data-status="contacted">Marcar contactada</button><button class="btn small" data-request="${r.id}" data-status="closed">Cerrar solicitud</button></div></article>`).join(''):'<p class="muted">No hay solicitudes registradas en esta bandeja.</p>';}
function field(name,label,value='',type='text',extra=''){return `<div class="field"><label for="f-${name}">${esc(label)}</label><input id="f-${name}" name="${name}" type="${type}" value="${esc(value??'')}" ${extra}></div>`;}
function area(name,label,value='',required=false){return `<div class="field span2"><label for="f-${name}">${esc(label)}</label><textarea id="f-${name}" name="${name}" maxlength="2000" ${required?'required':''}>${esc(value||'')}</textarea></div>`;}
function checkbox(name,label,checked=false){return `<label class="check"><input name="${name}" type="checkbox" ${checked?'checked':''}>${esc(label)}</label>`;}
function select(name,label,options,value=''){return `<div class="field"><label for="f-${name}">${esc(label)}</label><select id="f-${name}" name="${name}">${options.map(([v,l])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(l)}</option>`).join('')}</select></div>`;}
function showEditor(type,id,title,html){editing={type,id};$('editor-title').textContent=title;$('editor-fields').innerHTML=html;$('editor-result').textContent='';$('editor').showModal();}
function editPartner(id){const p=partners.find(x=>x.id===id)||{};showEditor('partner',id,id?'Editar empresa':'Agregar empresa',field('name','Nombre de empresa',p.name,'text','required minlength="2" maxlength="180"')+field('slug','Identificador (minúsculas y guiones)',p.slug,'text','required pattern="[a-z0-9-]{2,80}"')+field('category','Categoría',p.category||'Comercio','text','required maxlength="80"')+field('discount_percent','Descuento (%) — dejar vacío si no aplica',p.discount_percent,'number','min="0" max="100" step="0.01"')+field('benefit_title','Título del beneficio',p.benefit_title,'text','required maxlength="200"')+field('website','Sitio web HTTPS',p.website,'url')+field('whatsapp','WhatsApp (código país + número)',p.whatsapp,'text','maxlength="20"')+field('address','Dirección o sedes',p.address,'text','maxlength="400"')+field('logo_url','URL del logo o ruta dentro de la app',p.logo_url)+field('secondary_logo_url','Segundo logo (opcional)',p.secondary_logo_url)+field('starts_on','Inicio del convenio',p.starts_on||today(),'date','required')+field('ends_on','Término (opcional)',p.ends_on,'date')+area('description','Descripción de la empresa',p.description)+area('conditions','Condiciones del beneficio',p.conditions,true)+checkbox('active','Publicar ficha del convenio',p.active)+checkbox('featured','Destacar empresa',p.featured));}
function editAgreement(id){const a=agreements.find(x=>x.partner_id===id)||{};showEditor('agreement',id,'Acuerdo privado de aporte',select('contribution_type','Modalidad',Object.entries(typeLabels),a.contribution_type||'pending')+field('amount','Monto CLP (vacío cuando no está acordado)',a.amount,'number','min="0" step="1"')+select('status','Estado',Object.entries(stateLabels),a.status||'draft')+select('treasury_unit_id','Tesorería responsable',[['','Pendiente de asignar'],...units.map(u=>[u.id,u.name])],a.treasury_unit_id||'')+area('terms','Acuerdo, periodicidad y alcance',a.terms,true)+'<p class="small muted span2">No genera cargos ni movimientos de Tesorería. Registrar un acuerdo no acredita que el club haya recibido dinero.</p>');}
function editPromo(id){if(!partners.length){result($('admin-result'),'Primero agrega la empresa.',true);return;}const p=promos.find(x=>x.id===id)||{};showEditor('promo',id,id?'Editar promoción':'Nueva promoción',select('partner_id','Empresa',partners.map(x=>[x.id,x.name]),p.partner_id||partners[0].id)+field('title','Título',p.title,'text','required minlength="2" maxlength="180"')+select('audience','Público',[['members','Miembros vigentes'],['public','Público general']],p.audience||'members')+field('starts_on','Inicio',p.starts_on||today(),'date','required')+field('ends_on','Fin',p.ends_on,'date','required')+area('description','Contenido y condiciones',p.description,true)+checkbox('active','Publicar durante las fechas indicadas',p.active));}
$('editor-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;if(!form.reportValidity()||!editing)return;const f=new FormData(form),get=k=>String(f.get(k)||'').trim(),button=form.querySelector('button[type=submit]');if(button.disabled)return;button.disabled=true;const {type,id}=editing;try{
 let q;
 if(type==='partner'){
  for(const key of ['website','logo_url','secondary_logo_url'])if(get(key)&&!safeUrl(get(key),root))throw new Error('Los enlaces deben usar HTTPS o una ruta de la aplicación.');
  if(get('ends_on')&&get('ends_on')<get('starts_on'))throw new Error('La fecha de término no puede ser anterior al inicio.');
  const p=Object.fromEntries(['name','slug','category','benefit_title','website','whatsapp','address','logo_url','secondary_logo_url','starts_on','description','conditions'].map(k=>[k,get(k)]));p.ends_on=get('ends_on')||null;p.discount_percent=get('discount_percent')===''?null:Number(get('discount_percent'));p.active=f.has('active');p.featured=f.has('featured');p.updated_at=new Date().toISOString();
  q=id?sb.from('benefit_partners').update(p).eq('id',id).select('id').single():sb.from('benefit_partners').insert(p).select('id').single();
 }else if(type==='agreement'){
  const a={partner_id:id,contribution_type:get('contribution_type'),amount:get('amount')===''?null:Number(get('amount')),status:get('status'),treasury_unit_id:get('treasury_unit_id')||null,terms:get('terms'),updated_at:new Date().toISOString()};
  if(a.status==='approved'&&(!a.treasury_unit_id||a.contribution_type==='pending'||(['monthly','annual'].includes(a.contribution_type)&&!(a.amount>0))))throw new Error('Para aprobar, define modalidad, tesorería y monto cuando corresponda.');
  q=sb.from('benefit_agreements').upsert(a,{onConflict:'partner_id'}).select('partner_id').single();
 }else{
  if(get('ends_on')<get('starts_on'))throw new Error('Revisa las fechas de la promoción.');const p={partner_id:get('partner_id'),title:get('title'),description:get('description'),audience:get('audience'),starts_on:get('starts_on'),ends_on:get('ends_on'),active:f.has('active')};
  q=id?sb.from('benefit_promotions').update(p).eq('id',id).select('id').single():sb.from('benefit_promotions').insert(p).select('id').single();
 }
 const r=await q;if(r.error)throw r.error;$('editor').close();result($('admin-result'),'Cambios guardados en la base de datos.');try{await refresh();}catch{result($('admin-result'),'Guardado confirmado. Recarga la página para actualizar la vista.',true);}
 }catch(e){result($('editor-result'),e.message||'No fue posible guardar los cambios.',true);}finally{button.disabled=false;}});
$('close-editor').onclick=$('cancel-editor').onclick=()=>$('editor').close();
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.tab){document.querySelectorAll('[data-tab]').forEach(x=>x.setAttribute('aria-selected',String(x===b)));['partners','promos','hinchas','companies'].forEach(t=>$('panel-'+t).hidden=t!==b.dataset.tab);}
 if(b.dataset.editPartner)editPartner(b.dataset.editPartner);if(b.dataset.agreement)editAgreement(b.dataset.agreement);if(b.dataset.editPromo)editPromo(b.dataset.editPromo);
 if(b.dataset.request){if(b.disabled)return;b.disabled=true;try{const r=await sb.from('sponsor_inquiries').update({status:b.dataset.status,updated_at:new Date().toISOString()}).eq('id',b.dataset.request).eq('project_code','BENEFICIOS').select('id').single();if(r.error)throw r.error;await refresh();result($('admin-result'),'Estado de seguimiento actualizado. No activa membresías ni registra pagos.');}catch(err){result($('admin-result'),'No se pudo actualizar el estado. Recarga y vuelve a intentarlo.',true);}finally{b.disabled=false;}}
});
$('new-partner').onclick=()=>editPartner(null);$('new-promotion').onclick=()=>editPromo(null);
(async()=>{try{sb=client();const {data,error}=await sb.auth.getSession();if(error)throw error;if(!data.session){location.replace('login.html?next=beneficios.html');return;}const r=await sb.from('profiles').select('role,active').eq('user_id',data.session.user.id).maybeSingle();if(r.error)throw r.error;if(!r.data?.active||!['superadmin','board'].includes(r.data.role)){$('access-state').textContent='Este módulo está reservado a la directiva autorizada. La gestión no está disponible para esta cuenta.';return;}await refresh();$('access-state').hidden=true;$('admin-app').hidden=false;}catch(e){$('access-state').textContent='No pudimos verificar o cargar el módulo. Recarga la página; no se han cambiado datos.';}})();
